name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: vinay0410/tectonic-action@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        with:
          tex_path: 4M21-Software-Engineering-and-Design/main.tex
          push: 'yes'
